-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Erstellungszeit: 17. Aug 2017 um 14:49
-- Server-Version: 10.1.25-MariaDB
-- PHP-Version: 5.6.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `books`
--
CREATE DATABASE IF NOT EXISTS `books` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `books`;

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `items`
--

CREATE TABLE `items` (
  `id` int(11) NOT NULL,
  `isbn` varchar(13) NOT NULL,
  `title` varchar(50) NOT NULL,
  `author` varchar(70) NOT NULL,
  `publisher` varchar(50) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Daten für Tabelle `items`
--

INSERT INTO `items` (`id`, `isbn`, `title`, `author`, `publisher`, `image`, `description`) VALUES
(1, '9783257018738', 'Schaltjahr', 'Peter Cameron', 'Diogenes', 'https://images-na.ssl-images-amazon.com/images/I/41KOixCcGTL._SX300_BO1,204,203,200_.jpg', ''),
(2, '9783257230116', 'Guru: Roman', 'Andrea DeCarlo', 'Diogenes', 'https://images-na.ssl-images-amazon.com/images/I/41rYOoyagjL._SX312_BO1,204,203,200_.jpg', 'Andrea De Carlo, geboren am 11. Dezember 1952 in Mailand, lebte nach einem Literaturstudium längere Zeit in den USA und Australien. Er war Fotograf, Maler und Rockmusiker, bevor er 1981 seinen ersten Roman, \'Creamtrain\', schrieb - gleichzeitig auf italienisch und englisch. Später war er Regieassistent von Federico Fellini, drehte für die RAI den Dokumentarfilm \'Le facce di Fellini\' und schrieb daneben für das Feuilleton des \'Corriere della Sera\'. Andrea De Carlo lebt in Rom, Mailand und auf dem Land in der Nähe von Urbino.'),
(3, '9783404128150', 'Die Brücken der Freiheit.', 'Ken Follett und Till R. Lohmeyer', 'Bastei Lübbe (28. April 1998)', 'https://images-na.ssl-images-amazon.com/images/I/515gObYqTSL._SX350_BO1,204,203,200_.jpg', 'Vom alten England bis in die Neue Welt spannt sich der große Bogen des abenteuerlichen Lebens zweier Menschen auf der Suche nach Freiheit. In den schottischen Kohlengruben herrscht das Gesetz der Sklaverei. Doch Mack McAsh, ein junger Bergmann, träumt davon, frei zu sein.  Er flieht nach London - und gerät in eine andere Form von Knechtschaft: Als Aufrührer verurteilt, wird er in Ketten nach Virginia verschifft. Dort trifft er auf Lizzie Jamisson, die Frau, die ihm einst zur Flucht verholfen hat und dabei ihr eigenes Glück als Preis zahlte.'),
(4, '9783404612338', 'Und besiege die Finsternis', 'Marie Balter und Richard Katz', 'Bastei Lübbe (März 1999)', 'https://images-na.ssl-images-amazon.com/images/I/31BB5DHSD6L._BO1,204,203,200_.jpg', ''),
(5, '9783423084048', 'Der englische Patient', 'Ondaatje Michael', 'dtv; Auflage: 6. (Mai 1997)', 'https://images-na.ssl-images-amazon.com/images/I/41ZVKW3NHHL._SX295_BO1,204,203,200_.jpg', '»Geschichten von Menschen, die vom Krieg und von der Liebe heimgesucht werden. Ein großartiges Werk von unwiderstehlicher Faszination.« Don DeLillo   ›Der englische Patient‹ erhielt 1992 den Booker Prize und wurde 1996 durch die kongeniale Verfilmung Anthony Minghellas weltberühmt: In einer zerbombten Villa in der Nähe von Florenz treffen gegen Ende des Zweiten Weltkrieges vier Menschen aufeinander: Caravaggio, einst ein Dieb, der für die Alliierten spioniert hat, Kip, ein junger Sikh, Spezialist für das Entschärfen von Bomben, Hana, eine kanadische Krankenschwester – und der englische Patient Almásy, ein Flieger, der über der nordafrikanischen Wüste abgeschossen wurde.'),
(6, '9783423129718', 'Was am Ende bleibt: Roman', 'Paula Fox und Sylvia Höfer', 'dtv Verlagsgesellschaft (1. Mai 2002)', 'https://images-na.ssl-images-amazon.com/images/I/41TRoqOkr6L._SX312_BO1,204,203,200_.jpg', '»Paula Fox schreibt wirklich meisterhaft.«  ›Der Spiegel‹  Psychogramm einer Ehe: Seit fünfzehn Jahren verheiratet, beruflich erfolgreich, kinderlos, wohlsituiert, sind Sophie und Otto Bentwood der Inbegriff eines arrivierten Ehepaars der gehobenen Mittelschicht New Yorks. Unausgesprochen, und doch in jedem Satz spürbar, sind die unterschwelligen Spannungen, die unter der glatten Oberfläche der scheinbar harmonischen Beziehung arbeiten. Erste Risse werden sichtbar, als Ottos Geschäftspartner im Streit aus der gemeinsamen Anwaltskanzlei ausscheidet. Obgleich Otto den Vorfall herunterzuspielen versucht, greift die berufliche Krise mehr und mehr auf seine Ehe über.   Sophies Unbehagen, ihre vage Angst vor einem Erstarren der Beziehung wie vor möglicherweise einschneidenden Veränderungen, verdichtet sich zu einem akuten Gefühl der Bedrohung. Mehrere halbherzige Ausbruchversuche enden in der Sackgasse, die Situation bleibt auf beklemmende Weise in der Schwebe. Ob die Krise eine rasch überwundene Episode sein wird, oder ob sie droht, die berufliche und private Existenz des Paares zu zerstören, bleibt offen.   Die Wiederentdeckung von Paula Fox‘ 1971 zuerst erschienenem Roman war in den USA eine literarische Sensation. Das Buch wurde als eines der wichtigsten amerikanischen Werke des 20. Jahrhunderts gefeiert. Nun liegt das schmale Meisterwerk endlich in deutscher Übersetzung vor und hat auch hierzulande seinen Siegeszug bei Lesern wie Kritikern angetreten.'),
(7, '9783426601525', 'Der Diamant des Salomon', 'Noah Gordon und Thomas A. Merk', 'Knaur; Auflage: 1. (September 1993)', 'https://images-na.ssl-images-amazon.com/images/I/51XH25WEY6L._SX291_BO1,204,203,200_.jpg', 'Genisa  Immer wenn Baruch erwachte, erwartete er, verhaftet zu werden. Die leere Schriftrolle bestand aus gutem Kupfer, das so lange gehämmert worden war, bis es so dünn und glatt wie ein Stück Leder war. Sie steckten sie in einen Sack und brachten sie, heimlich wie die Diebe, die sie ja eigentlich auch waren, zu ihrem Versteck am Rand eines verlassenen Stoppelfelds. Im Inneren der kleinen Höhle war es trotz des stahlblauen Himmels draußen, der durch den Eingang zu sehen war, dunkel, und so füllte Baruch die Lampe mit Öl, zündete sie an und stellte sie auf einen flachen Stein.  Drei der jüngeren Verschwörer hielten draußen Wache, indem sie mit einem Schlauch Wein Betrunkene spielten. Der alte Mann in der Höhle hörte sie kaum. Er spürte wieder den Schmerz in der Brust, und seine Hände zitterten, als er sich zwang, den Schlegel und die Ahle zu ergreifen. Dies sind die Worte des Baruch, Sohn des Neriah ben Maasiah, Sproß der Priester aus Anatoth im Lande Benjamins, der im neunten Jahr der Regierung des Zedekiah, Sohn des Josias, König von Judäa, von Jeremias, dem Sohn des Hilkiahu Kohen den Befehl erhielt, den Schatz des Herrn zu verstecken.'),
(8, '9783442151134', 'Gefangen in den Gärten', 'Fatema Oufkir und Kristiana Ruhl', 'Goldmann; Auflage: Goldmann (2000)', 'https://images-na.ssl-images-amazon.com/images/I/21VWQJEAPWL._BO1,204,203,200_.jpg', ''),
(9, '9783442353996', 'Und sonntags aufs Land:', 'Maeve Haran und Ariane Böckler', 'Blanvalet Taschenbuch Verlag; Auflage: Blanvalet T', 'https://images-na.ssl-images-amazon.com/images/I/412NQPKY32L._SX298_BO1,204,203,200_.jpg', 'Catherine Stone, a mother of two, worries about her 18-years old daughter Rachel. Even now — on the verge of her high school graduation — Rachel has fallen in love with a man who does not fit in the family at all. In addition to his passion for Rachel, Marko is equally as passionate about his militant activities and begins interfering with the grandmother Lavinia’s business….  Stirnrunzelnd beobachtet Catherine Stone, sturmerprobte Mutter zweier Kinder, ihre 18-jährige Tochter Rachel. Ausgerechnet jetzt, kurz vor dem Abitur, ist diese wild entschlossen, einem jungen Mann ihre Jungfräulichkeit zu schenken, der so gar nicht in die friedliche Familie passt. Denn außer seiner Leidenschaft für Rachel hat dieser Marko noch eine ausgeprägte Passion: militante Öko-Aktionen. Womit er nicht nur Großmutter Lavinia in die Quere kommt, die sich soeben einer Bürgerinitiative angeschlossen hat ...'),
(10, '9783442376162', 'Die Antwort des Windes', 'Eliza Graham und Elfriede Peschel', 'Blanvalet (17. Januar 2011)', 'https://images-na.ssl-images-amazon.com/images/I/51dMeO7HOLL._SX340_BO1,204,203,200_.jpg', 'Eine bewegende Familiensaga über dunkle Geheimnisse, tiefe Gefühle – und ein überraschendes Wiedersehen!  Ganz England feiert das Goldene Thronjubiläum der Queen. Auch Rachel Parr und ihre Tante Evie haben sich unter die fröhlichen Dorfbewohner gemischt. Doch sie können nicht vergessen, was vor genau fünfundzwanzig Jahren geschah: Evies Tochter Jessamy verschwand spurlos. Kurz darauf erhält Rachel die Nachricht von Evies plötzlichem Tod. Sie kehrt auf die Farm in den Cotswolds zurück, um den Nachlass zu ordnen. Ihre bittersüßen Erinnerungen bringen sie auf die Spur eines schier unglaublichen Familiengeheimnisses …'),
(11, '9783442480722', 'Nein! Ich möchte keine', 'Virginia Ironside und Sibylle Schmidt', 'Goldmann Verlag (17. Juni 2014)', 'https://images-na.ssl-images-amazon.com/images/I/51mU7cZ-frL._SX332_BO1,204,203,200_.jpg', 'Marie Sharp ist mittlerweile fast 65, und sie hat eine Liste mit guten Vorsätzen: Nie wieder Alkohol trinken, ein Facelifting machen lassen, Akupunktur ausprobieren und natürlich: Tagebuch schreiben, denn Maries leben ist völlig aus dem Gleichgewicht geraten. Ihre Jugendliebe Archie ist an Alzheimer erkrankt und glaubt an Elefanten im Schrank, und ihr Sohn Jack beschließt, mit seiner Familie in die Staaten zu ziehen. Selbst Video-Telefonate helfen nicht gegen Maries Sehnsucht, und so macht sie sich schließlich auf die Reise ins Land der unbegrenzten Möglichkeiten ...'),
(12, '9783442722495', 'Schnee, der auf Zedern', 'David Guterson und Christa Krüger', 'btb; Auflage: 2. (Februar 1998)', 'https://images-na.ssl-images-amazon.com/images/I/41FDPEBEVPL._SX294_BO1,204,203,200_.jpg', 'Der Roman spielt auf der Insel San Piedro nach dem Zweiten Weltkrieg. Ein mysteriöser Mordfall läßt alte Familienfehden, Jugendlieben und die im Weltkrieg entstandenen Spannungen zwischen der japanischen und angelsächsischen Inselbevölkerung wieder aufleben. Der Hauptverdächtige, gegen den alle Indizien sprechen, ist der japanische Lachsfischer Kabuo. Ishmael Chambers, Reporter, Redakteur und Herausgeber der einzigen Zeitung der Insel, versucht den Hergang des Verbrechens zu rekonstruieren. Wie der stetig fallende Schnee die Landschaft verändert, so verdichten sich Hinweise und Indizien, bis am Ende von Chambers\' geduldiger Suche die Wahrheit steht.'),
(13, '9783442723300', 'Die rote Couch. Roman', 'Irvin D. Yalom und Michaela Link', 'Goldmann; Auflage: 24. (Oktober 1998)', 'https://images-na.ssl-images-amazon.com/images/I/41AdE6f1-ZL._SX314_BO1,204,203,200_.jpg', 'Ernest Lash, ein junger Psychoanalytiker aus San Francisco, glaubt an die Wirksamkeit seines Tuns, ist aber andererseits davon überzeugt, daß die klassischen Therapien dringend einer Erneuerung bedürfen. Eines Tages beauftragt ihn die Ethikkommission seines Fachbereichs mit der Untersuchung eines prekären Falls: Er soll die Arbeitsweise eines älteren, sehr berühmten Kollegen namens Seymour Trotter überprüfen, der angeklagt ist, ein Verhältnis mit einer vierzig Jahre jüngeren Patientin gehabt zu haben. Trotter beharrt darauf, daß Sex das einzige Mittel gewesen sei, um die junge Frau vor ihrem selbstzerstörerischen Verhalten zu retten. Zunächst ist Ernest entrüstet.'),
(14, '9783446178205', 'Der Plan von der', 'Peter Høeg und Angelika Gundlach', 'Carl Hanser; Auflage: 9 (1. Januar 1995)', 'https://images-na.ssl-images-amazon.com/images/I/411TA11SSSL._SX301_BO1,204,203,200_.jpg', 'Drei Waisenkinder begegnen sich in einer Kopenhagener Privatschule. Nach und nach erfahren sie deren ausgeklügeltes System aus Überwachung und Manipulation und bilden eine Art Ersatzfamilie. Wie Fräulein Smillas Gespür für Schnee schildert dieser spannende, autobiographisch motivierte Roman den Kampf von Outsidern gegen eine grausame Machthierarchie und erzählt zugleich eine zarte, ergreifende Liebesgeschichte.'),
(15, '9783451065767', 'Das Hängemattenbuch:', 'German Neundorfer', 'Verlag Herder; Auflage: 1 (15. April 2013)', 'https://images-na.ssl-images-amazon.com/images/I/415Uv4XN8PL._SX314_BO1,204,203,200_.jpg', 'Ausspannen, entspannen, genießen. Gerade rechtzeitig fürs Frühjahr und den Sommerbeginn erzählt das neue Hängemattenbuch Geschichten vom Leben und der Liebe, vom Fernweh und vom Zuhausebleiben, von kleinen und von großen Abenteuern, vom Glück und davon, was man damit anfängt. Mit Geschichten, Erinnerungen, Erzählungen und Nachdenkereien von • Margot Käßmann • Frank Elstner • Siegfried Rauch • Joel ben Izzy • und vielen anderen'),
(16, '9783453358508', 'Blaues Blut: Ein Fall für', 'Felicitas Gruber', 'Diana Verlag (13. Juli 2015)', 'https://images-na.ssl-images-amazon.com/images/I/51Y5UMuiDLL._SX314_BO1,204,203,200_.jpg', 'Hochsommer in München. Die Stadt glüht. Ebenso wie die neu erwachte Liebe zwischen der Rechtsmedizinerin Dr. Sofie Rosenhuth und Hauptkommissar Joe Lederer. Doch die Leiche einer alleinstehenden Adligen, verblutet in der eigenen Badewanne, verhindert, dass die beiden von einer zweiten Hochzeit träumen können. Zumal Sofies Verehrer, Charly Loessl, mit besagter Dame verheiratet war und nun ihre Hilfe braucht. Aber hat der smarte Polizeireporter noch mehr zu verbergen als seinen Adelstitel?  Ein neuer Fall für die narrisch erfolgreiche Rechtsmedizinerin Dr. Sofie Rosenhuth'),
(17, '9783453430082', 'Und morgen in das kühle', 'Mary Higgins Clark und Andreas Gressmann', 'Heyne Verlag; Auflage: Heyne Verlag (1. Januar 200', 'https://images-na.ssl-images-amazon.com/images/I/41DqIe5yMvL._SX318_BO1,204,203,200_.jpg', 'Ein Spannungsroman der Extraklasse: Das spurlose Verschwinden von Nicholas Spencer, Leiter eines bedeutenden pharmazeutischen Forschungslabors, stellt die Welt vor ein Rätsel. Kurz darauf wird überraschend enthüllt, dass Spencer die Firma um Millionen betrogen hatte. Die Journalistin Marcia DeCarlo wagt sich bei ihren Recherchen zu weit vor – und begibt sich damit in Lebensgefahr.'),
(18, '9783453877917', 'Die Entscheidung: Roman', 'Vince Flynn und Norbert Jakober', 'Heyne Verlag (5. Juli 2004)', 'https://images-na.ssl-images-amazon.com/images/I/51EEfQFj90L._SX314_BO1,204,203,200_.jpg', 'Mitch Rapp, der beste Anti-Terror-Agent der CIA, wird bei einer gefährlichen Mission in Deutschland von seinen Auftraggebern verraten. Es gelingt ihm, der tödlichen Falle zu entkommen und in die USA zurückzukehren. Dort versucht er, die Hintermänner, die ihn ausschalten wollten, zu fassen, und kommt einer politischen Verschwörung auf höchster Ebene auf die Spur.'),
(19, '9783462015713', 'Florenz.', 'Mary McCarthy', 'Kiepenheuer & Witsch GmbH (Juli 1991)', 'https://images-na.ssl-images-amazon.com/images/I/412I8R41%2BSL._SX373_BO1,204,203,200_.jpg', ''),
(20, '9783475523397', 'Bloß net aus da Ruah', 'Helmut Zöpfl', 'Rosenheimer Verlagshaus; Auflage: Rosenheimer Verl', 'https://images-na.ssl-images-amazon.com/images/I/31rphTALXyL._BO1,204,203,200_.jpg', 'Auf seine liebenswerte Art – einmal grantelnd, dann wieder hintersinnig schmunzelnd – macht sich der beliebte Münchner Autor hier Gedanken über verschiedene menschliche und allzu menschliche Themen. So z. B. über den Fortschritt, über die heutige Art, Kinder zu erziehen, oder über die schönsten Wochen des Jahres – den Urlaub. Und ganz nebenbei entwickelt er seine eigene Lebensphilosophie – eine typisch bayerische: \"Bloß nicht aus der Ruh bringen lassen!\"'),
(21, '9783492232142', 'Weihnachten für freche', 'Gaby Hauptmann und Marianne Weissberg', 'Piper Verlag, (2001)', 'https://images-na.ssl-images-amazon.com/images/I/41ANXMN0SGL._SX307_BO1,204,203,200_.jpg', ''),
(22, '9783492258081', 'Beim Leben meiner', 'Jodi Picoult und Ulrike Wasel', 'Piper Taschenbuch; Auflage: 15 (1. August 2009)', 'https://images-na.ssl-images-amazon.com/images/I/51p5D5GnyDL._SX314_BO1,204,203,200_.jpg', '»Tief bewegend und spannend wie ein Krimi.« Für Sie Ohne ihre Schwester Anna kann Kate Fitzgerald nicht leben: Sie hat Leukämie. Doch als Anna 13 Jahre alt ist, weigert sie sich, weiterhin Knochenmark für ihre todkranke Schwester zu spenden. Für sie besteht kein Zweifel mehr, dass sie nur geboren worden ist, um ihrer Schwester das Leben zu retten. Aber Anna beginnt sich zu fragen, wer sie wirklich ist. Und sie beschließt nun, ihr Schicksal selbst in die Hand zu nehmen – ein Anwalt soll dafür sorgen, dass sie ihren Körper nie mehr für Kate zur Verfügung stellen muss …'),
(23, '9783499228315', 'Auferstehung der Toten', 'Wolf Haas', 'Rowohlt Taschenbuch Verlag; Auflage: 27 (1. August', 'https://images-na.ssl-images-amazon.com/images/I/61NFAAY%2Bc3L._SX301_BO1,204,203,200_.jpg', 'In Zell am See geht es etwas langsamer zu als im Rest der Welt. Hier wird man nicht erschossen., sondern tiefgefroren. So ist es einem steinreichen amerikanischen Ehepaar ergangen, das man an einem klirrend kalten Wintermorgen in einem Sessellift findet. Die Polizei beißt sich an der Sturheit der Zeller schnell die Zähne aus. Licht in diesen Fall kann nur ein Mann wie Privatdetektiv Brenner bringen, ein ehemaliger Polizist, der wegen seiner nervenzermürbenden Langsamkeit aus dem Job geekelt wurde. Brenner hat das Gespür für den Rhythmus der österreichischen Provinz.'),
(24, '9783499236143', 'Freizeichen', 'Ildikó von Kürthy', 'Rowohlt; Auflage: 21 (3. Mai 2004)', 'https://images-na.ssl-images-amazon.com/images/I/41KvzSyc8GL._SX327_BO1,204,203,200_.jpg', '«Ein Luftballon zum Lesen. Feinste Lach-Delikatesse!» BILD  Eine Frau die sich langweilt, ist zu allem fähig: Annabel hat seit Jahren denselben Mann und dieselbe Frisur. Sie ist einunddreißig und will endlich was erleben. An einem Sonntagmorgen reist sie nach Mallorca. Am Sonntagabend ist sie verliebt. Glaubt sie. Bis am Dienstag eine Konkurrentin auftaucht. Die ist dünn und liebt den Mann, den Annabel gerade verlassen will. Und das ändert natürlich alles!'),
(25, '9783499242229', 'Das letzte Königreich', 'Bernard Cornwell und Michael Windgassen', 'Rowohlt; Auflage: 23 (2. Januar 2007)', 'https://images-na.ssl-images-amazon.com/images/I/51g36iBAhTL._SX301_BO1,204,203,200_.jpg', 'Mit den Drachenbooten kommt der Tod  Nordengland im Jahre 866: Mit zehn Jahren erlebt der Fürstensohn Uhtred den Einfall der Wikinger. Sein ungestümer Mut in der Schlacht beeindruckt den Anführer der Dänen so sehr, dass er Uhtred verschont und als Ziehkind aufnimmt. Mit den Jahren wird der Junge fast einer von ihnen. Nach Raub- und Eroberungszügen voller Blut und Gewalt droht auch Wessex, das letzte der fünf angelsächsischen Königreiche, an die Eroberer zu fallen. Doch da wechselt Uhtred wieder die Seiten.'),
(26, '9783499626708', 'Föhn mich nicht zu. Aus', 'Stephan Serin und Ulrich Scheel', 'Rowohlt Taschenbuch Verlag; Auflage: 7. Auflage 20', 'https://images-na.ssl-images-amazon.com/images/I/510aTSgQXxL._SX327_BO1,204,203,200_.jpg', 'Die Leiden eines jungen Lehrers-Intelligent, ironisch, witzig!  «Um permanentes Chaos im Klassenraum zu vermeiden, muss den Schülern von der ersten Minute an klar sein, wer im Unterricht der Boss ist. In meiner siebten Klasse war das Murat. Aber danach kam gleich ich, denn ich war mit Murat befreundet.»'),
(27, '9783518460498', 'Die Stimmen des Flusses', 'Jaume Cabré und Kirsten Brandt', 'Suhrkamp; Auflage: 1. (20. Oktober 2008)', 'https://images-na.ssl-images-amazon.com/images/I/518dGf1T1-L._SX309_BO1,204,203,200_.jpg', 'Ein großer, dramatischer Roman über das engverflochtene Schicksal einer Handvoll Menschen, die der Spanische Bürgerkrieg zu Gegnern und zu Liebenden macht. Seit Carlos Ruiz Zafóns Der Schatten des Windes hat es keinen Roman aus Spanien gegeben, der seine Leser so in den Sog einer faszinierenden Geschichte zieht wie dieser.'),
(28, '9783522166102', 'Der satanarchäolügenialkohöllische Wunschpunsch', 'Michael Ende und Regina Kehn', 'K.Thienemanns; Auflage: 1. (1989)', 'https://images-na.ssl-images-amazon.com/images/I/51KYV6ZN2SL._SX319_BO1,204,203,200_.jpg', 'Silvester naht. Der Zauberer Beelzebub Irrwitzer und seine Tante Tyrannja Vamperl haben ein Problem: Ihr Soll an bösen Taten ist für dieses Jahr noch nicht erfüllt. Rabe Jakob und Kater Maurizio durchkreuzen ihre teuflischen Pläne und versuchen, eine Katastrophe zu verhindern. Ein Wettlauf mit der Zeit beginnt. Ob Rabe, Kater oder Hexenweib: Für jede dieser fantastischen Figuren findet Rufus Beck eine eigene, unverwechselbare Stimme!'),
(29, '9783530421866', 'Gelassenheit. Vom Umgang', 'Christiane Neuen und Verena Kast', 'Walter-Verlag (2004)', 'https://images-na.ssl-images-amazon.com/images/I/417QNG6936L._SX299_BO1,204,203,200_.jpg', 'Kommissar Erik Winters dritter und vierter Fall: In Das vertauschte Gesicht muss er bis an seine Grenzen gehen, um einen Mörder zu fassen, der es auf Winter selbst abgesehen hat. Nicht bis In alle Ewigkeit ruht ein ungeklärter Fall aus der Vergangenheit, denn der Serienkiller, den Winter jagt, trieb schon einmal sein Unwesen.'),
(30, '9783548027340', 'Letztes Jahr auf Ischia.', 'Christine Brückner', 'Ullstein Taschenbuchvlg., (1988)', 'https://images-na.ssl-images-amazon.com/images/I/51SwC4onmaL._SX298_BO1,204,203,200_.jpg', ''),
(31, '9783548364865', 'Maria, ihm schmeckt\'s', 'Jan Weiler', 'Ullstein; Auflage: 14. (2005)', 'https://images-na.ssl-images-amazon.com/images/I/41JP55G0CEL._SX301_BO1,204,203,200_.jpg', '»Als ich meine Frau heiratete, konnte ihre süditalienischeFamilie leider nicht dabei sein. Zuweit, zu teuer, zu kalt. Schade, dachte ich undöffnete ihr Geschenk. Zum Vorschein kam einmonströser Schwan aus Porzellan mit einem großenLoch im Rücken, in das man Bonbons füllt.Menschen, die einem so etwas schenken, mussman einfach kennen lernen.«Die herrlich komische Geschichte einer unglaublichenVerwandtschaft aus dem unbekanntenitalienischen Bundesland Molise, das laut seinerBewohner »am Arsch der Welt« liegt.'),
(32, '9783548373263', 'Sorry, wir haben die', 'Antje Blinda und Stephan Orth', 'Ullstein Taschenbuch (12. März 2010)', 'https://images-na.ssl-images-amazon.com/images/I/51Dv2ZBKDGL._SX314_BO1,204,203,200_.jpg', 'Vergessene Triebwerke, Piloten ohne Orientierung, Kühe auf der Landebahn: So manche Durchsage an Bord eines Flugzeugs treibt selbst erfahrenen Passagieren die Schweißperlen auf die Stirn. Hunderte von Lesern haben ihre Erlebnisse aus dem Cockpit an Spiegel Online geschickt – die besten und lustigsten Zitate und Anekdoten sind in diesem Buch versammelt. Also schnallen Sie sich an, klappen Sie die Tische hoch, und stellen Sie die Sitzlehnen aufrecht.'),
(33, '9783548611181', 'Liebe ist nichts für', 'Kristine Gasbarre und Theda Krohm-Linke', 'List Taschenbuch (14. Januar 2013)', 'https://images-na.ssl-images-amazon.com/images/I/41NkAkHKzeL._SX334_BO1,204,203,200_.jpg', 'Kristine Gasbarre führte ein erfolgreiches Leben in New York und Italien. Nur mit der Liebe klappte es nie so recht. Wo sind sie nur, die echten Männer, die wie ihr Großvater sechzig Ehejahre lang unverbrüchlich zu ihrer Frau und ihrer Familie stehen? Als Kristine in ihre kleine Heimatstadt zurückkehrt, um sich um ihre verwitwete Großmutter zu kümmern, bekommt sie von ihr überraschende Antworten: Eine Frau braucht keine Machtspielchen, keine Dating-Tipps und keine Checklisten für Mr. Right. Ihr Ehegeheimnis, so erzählt die Großmutter, waren Respekt, Geduld und Hingabe. Angeblich altmodische Liebeswerte, doch Kristine entdeckt: Wenn du weißt, wer du als Frau bist, findest du den richtigen, für dich perfekten Mann - und den Mut, ihn von ganzem Herzen zu lieben.'),
(34, '9783551580429', 'Tanz auf dünnem Eis', 'Pernilla Glaser', 'Carlsen (1999)', 'https://images-na.ssl-images-amazon.com/images/I/412RH2W60ML._SX295_BO1,204,203,200_.jpg', 'Sie ist einundzwanzig, er zweiundzwanzig, und sie lieben sich. Doch es bleiben ihnen nur achtzehn Monate – sie werden das Unglück nicht aufhalten können: Sein besiegt geglaubtes Krebsleiden bricht erneut aus. Beide nehmen den Kampf auf für ihre Liebe und für das kurze Stück Leben, das sie miteinander haben. Pernilla Glaser schrieb dieses ungewöhnliche Buch in einer knappen und eindringlichen Sprache, die diese Liebeserklärung an das Leben zu einer unvergesslichen Lektüre macht. – »Es ist vor allem die erschütternde Geschichte eines langsamen Todes. Bis zum Schluss allerdings versiegt das Aufbegehren gegen die Krankheit nicht, setzt sich die junge Autorin selbst noch in der Vitalität ihres Erzähltons der Resignation zur Wehr.«'),
(35, '9783596165674', 'Blasse Engel. Thriller', 'Anders Roslund und Börge Hellström', 'Fischer T; Auflage: 1. (Juni 2007)', 'https://images-na.ssl-images-amazon.com/images/I/41-pBUXsgdL._SX320_BO1,204,203,200_.jpg', ''),
(36, '9783596247509', 'Ein Mann für jede Tonart:', 'Hera Lind', 'FISCHER Taschenbuch; Auflage: 30 (1. Dezember 1989', 'https://images-na.ssl-images-amazon.com/images/I/51vKbnlNm4L._SX314_BO1,204,203,200_.jpg', ''),
(37, '9783596851164', 'Gyde und die Flut', 'Patricia Schröder', 'Fischer Taschenbuch; Auflage: 1 (2003)', 'https://images-na.ssl-images-amazon.com/images/I/41FBR773SJL._SX257_BO1,204,203,200_.jpg', ''),
(38, '9783608957945', 'Diagnose Krebs. Wendepunkt', 'Lawrence LeShan und Annegrete Lösch', 'Klett-Cotta; Auflage: 9 (1. Mai 2010)', 'https://images-na.ssl-images-amazon.com/images/I/415Tdk0Td4L._SX299_BO1,204,203,200_.jpg', 'Der große alte Mann der psychologischen Krebsforschung zieht die Summe seiner fast 40jährigen Erfahrung im psychotherapeutischen Umgang mit Krebspatienten.  LeShan ist der Nestor einer ganzheitlichen Krebstherapie, die den Bedürfnissen von Körper, Seele und Geist in gleicher Weise Rechnung trägt. Ein Buch für alle, die an Krebs leiden oder als Angehörige, Freunde, Ärzte oder Psychotherapeuten mit krebskranken Menschen zu tun haben.'),
(39, '9783720550420', 'Rolfing. Wie Sie Ihren', 'Peter Schwind', 'Hugendubel, Heinrich, Verlag; Auflage: Neuauflage ', 'https://images-na.ssl-images-amazon.com/images/I/41UhKD7zrkL._SX346_BO1,204,203,200_.jpg', 'Die Botschaft der Rolfing-Methode ist: Auch nach vielen Jahren mit Haltungsschäden, muskulären Dysbalancen oder Gelenkfehlstellungen ist es möglich, den Körper wieder ins richtige Lot zu bringen. Peter Schwind, einer der führenden Experten, erklärt in diesem Buch anschaulich und leicht verständlich, wie eine kompetente Behandlung für Patienten aussieht und was man selbst unterstützend tun kann, um wieder aufrecht und ohne Schmerzen durchs Leben zu gehen.'),
(40, '9783734104169', 'Das barmherzige Fallbeil:', 'Fred Vargas und Waltraud Schwarze', 'Blanvalet Taschenbuch Verlag (20. März 2017)', 'https://images-na.ssl-images-amazon.com/images/I/518Jf5rySjL._SX332_BO1,204,203,200_.jpg', 'Adamsberg ist zurück, und seine Ermittlungen führen ihn in die blutige Zeit der Französischen Revolution und in die tödliche Kälte Islands ...  Innerhalb weniger Tage werden zwei Leichen in Paris entdeckt. Die beiden Fälle scheinen nichts miteinander zu tun zu haben. Bis Adamsberg auf unauffällige Zeichnungen an den Tatorten aufmerksam wird und ein Brief auftaucht, der auf die Verbindung zwischen den beiden Opfern hinweist. Der Brief führt Adamsberg auf die Spuren einer verhängnisvollen Reise nach Island – sowie in die Untiefen einer Geheimgesellschaft, die sich Robespierre und der Französischen Revolution verschrieben hat. Weitere Menschen sterben, und für Adamsberg beginnt ein Wettrennen gegen einen ebenso wandelbaren wie unbarmherzigen Mörder …'),
(41, '9783762732716', 'Mathematische Formeln und', 'Barth Mühlbauer und Wörle Nikol', 'Bayerischer Schulbuch Verlag; Auflage: 7., Aufl. (', 'https://images-na.ssl-images-amazon.com/images/I/41ZNG67Z73L._SX293_BO1,204,203,200_.jpg', ''),
(42, '9783774231474', 'Meerschweinchen', 'Katrin Behrend und György Jankovics', 'Gräfe und Unzer; Auflage: 7. (2001)', 'https://images-na.ssl-images-amazon.com/images/I/718ATS4QYCL._SX378_BO1,204,203,200_.gif', 'Der Weg zur erfolgreichen Meerschweinchen-Haltung: alles über Anschaffung, Haltung, Pflege und Beschäftigung. Das Kinder-Extra bring spannende Informationen aus dem Leben des Meerschweinchens. Der unverzichtbare Ratgeber, damit sich die munteren Gesellen bei Ihnen so richtig wohlfühlen!'),
(43, '9783784418506', 'Abraham kann nichts', 'Gerhard Bronner und Ephraim Kishon', 'München ; Wien : Langen-Müller, (1985)', 'https://images-na.ssl-images-amazon.com/images/I/41NgWM9l39L._SX298_BO1,204,203,200_.jpg', ''),
(44, '9783789119521', 'Eine Woche voller Samstage', 'Paul Maar', 'Oetinger Verlag; Auflage: 27 (1. Februar 1973)', 'https://images-na.ssl-images-amazon.com/images/I/51SisIEgQeL._SX337_BO1,204,203,200_.jpg', 'Herr Taschenbier ist ein ängstlicher Mensch. Er fürchtet sich vor seiner Zimmerwirtin, vor seinem Chef und überhaupt vor allen Leuten, die schimpfen und befehlen - bis ihm eines Samstags ein Sams über den Weg läuft und kurzerhand beschließt, bei ihm zu bleiben. Das Sams ist ein furchtloses, ja beinahe respektloses Wesen, das sich von nichts und niemandem einschüchtern lässt, das überall freche Bemerkungen macht und zurückschimpft, wenn andere schimpfen. Herrn Taschenbier ist das anfangs furchtbar peinlich und er versucht auf alle möglichen Arten, das Sams wieder loszuwerden.Aber seltsam: Je länger es bei Herrn Taschenbier bleibt, desto lieber gewinnt er das Sams. Und am Schluss wird aus dem braven, ängstlichen Herrn Taschenbier ein selbstbewusster Mensch, der gelernt hat, sich zu behaupten. Mehr über das Sams: www.wunschpunkte.de'),
(45, '9783828023093', 'Angriff auf Ihr Geld: Der', 'Jürgen Wipfler und Markus Wipfler', 'Frieling Verlag Berlin; Auflage: 4. Auflage. (22. ', 'https://images-na.ssl-images-amazon.com/images/I/51-WEOCinRL._SX350_BO1,204,203,200_.jpg', 'Wie wird die Zukunft unseres Finanzsystems aussehen? Kommt es zum großen Crash der Finanzen? Welche Möglichkeiten hat der Sparer und Anleger, sein Vermögen möglichst sicher durch die kommenden Zeiten zu bringen?Wer um diese Dinge weiß, darf sich im Vorteil sehen. Das Buch wirft einen Blick auf Vorgänge des Finanzsystems, über die man nur selten Genaues hört: versteckte Schulden, inflationäre Geldmengen, Wirtschaftszyklen, den Lastenausgleich. Wichtige Vermögensarten werden von A bis Z auf ihre Widerstandsfähigkeit gegenüber Finanzkrisen untersucht. Die Thesen des Buches gehen einen Schritt weiter als die gegenwärtige Diskussion: mit Informationen, die einem Politiker, Medien und Banken derzeit (immer noch) verschweigen.'),
(46, '9783833935367', 'Cybersurfer - Angriff der', 'Collin McMahon und Jens Rotzsche', 'Baumhaus; Auflage: 1. (24. April 2010)', 'https://images-na.ssl-images-amazon.com/images/I/518MzS1gptL._SX314_BO1,204,203,200_.jpg', 'Mit einem falschen Klick setzt Ennis alle Computer im Elektronikladen seines Onkels außer Gefecht. Die drakonische Strafe folgt auf dem Fuß: PC-Verbot. Am Rechner seines Freundes Mülli begeben sich die beiden Jungs auf die Suche nach der Ursache der PC-Abstürze. Sie stoßen auf den rätselhaften Binhexer, verfolgen dessen IP-Adresse zurück und decken so den Ursprung der Hackerangriffe auf. Noch ahnen sie nicht, wer wirklich hinter den Angriffen steckt: Der Elektronikriese Immens AG -'),
(47, '9783863340414', 'Bis auf den letzten', 'Iris Lieser', 'adeo (25. April 2015)', 'https://images-na.ssl-images-amazon.com/images/I/51z9XgbD7BL._SX312_BO1,204,203,200_.jpg', 'Als der Arzt Peter Lieser mit 38 Jahren die Diagnose \"Darmkrebs\" gestellt bekommt, wissen er und seine Frau Iris gleich, was dies bedeutet. Ihnen ist bald klar: \"Uns bleibt nur noch ein Jahr.\"  Denn der bösartige Tumor hat bereits gestreut, im gesamten Körper finden sich Tochterzellen, eine OP ist unmöglich und die Chemotherapie höchstens ein Spiel auf Zeit. Der Alltag der Familie mit drei kleinen Kindern ändert sich schlagartig. Was ist jetzt wichtig? Und vor allem stellt sich ihnen die Frage: Wie wollen wir die letzte Wegstrecke miteinander gehen?   Mit großem Einfühlungsvermögen und in bewegenden Worten schildert die Autorin die letzten Monate - Momente des Hoffens und der Freude, aber auch die innere Zerrissenheit. In ihren Gesprächen und bei gemeinsamen Erlebnissen findet das Paar eine bis dahin nicht gekannte Nähe. Das Leben wird intensiv und kostbar. Sie gehen den Weg gemeinsam - bis auf den letzten Schritt.'),
(48, '9783892876045', 'Anders als gedacht -', 'Friedhelm König', 'CSV; Auflage: 1 (2008)', 'https://images-na.ssl-images-amazon.com/images/I/51%2BuBQbFHHL._SX307_BO1,204,203,200_.jpg', ''),
(49, '9783898975742', 'Gold in den roten Bergen:', 'Heinz G Konsalik', 'Weltbild; Auflage: 1., Aufl. (8. Januar 2007)', 'https://images-na.ssl-images-amazon.com/images/I/51YNNpl6MOL._SX380_BO1,204,203,200_.jpg', ''),
(50, '9783570551943', 'Mein verwundetes Herz', 'Martin Doerry', 'Pantheon Verlag (27. August 2012)', 'https://images-na.ssl-images-amazon.com/images/I/51U1O0OL67L._SX310_BO1,204,203,200_.jpg', 'In einzigartiger Vollständigkeit sind über 500 Briefe erhalten, die das dramatische Schicksal einer deutsch-jüdischen Familie erzählen. Als die Jüdin Lilli Jahn verhaftet wird, halten allein die Kinder fest zu ihrer Mutter und schicken fast täglich Briefe ins Lager, die Lilli auf herausgeschmuggelten Papieren erwidert. Im März 1944 wird Lilli Jahn nach Auschwitz deportiert und stirbt dort.');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `items`
--
ALTER TABLE `items`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `isbn` (`isbn`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `items`
--
ALTER TABLE `items`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
